# -*- coding: utf-8 -*-
"""Assignment 1 notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O3nBQScRWrR7SagGZJjK6hgg4U6QtMqL

<span class="minerva-question" style="background-color:#f15a24;color:white;padding: 5px 20px 5px 20px;line-height:30px;height:30px;border-radius:3px">Important Note</span> For guidance on how to write in markdown, please consult [this documentation](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html).

# 1. Introduction

You should write your assignment introduction here.

I will utilize all of my understanding in this unit  to solve three problems in this assignment by first creating a flow chart and a pseudo-code, and then running the code. Data types, chained and nested conditionals, data conversions, boolean expressions, and (if,elif,else) statements will all be required to generate the code and print the necessary information.
---



---





---

## 1.1 Step-By-Step Algorithm

[link text](https://)Write each step of the algorithm you are proposing to solve the assignment problem here.

problem one:
i will first identify my variables as (a) for the delivery option which will be either express delivery , standard delivery or permium delivery and (b)for the weight of the package and both will ask the user to input their choice. And then I will use chained conditionals so first i will add an if statement and then continue the following with four elif statements until i reach the last option; i will use an else statement as the end part to print the last statement.(Within all the statments i have used Booleon expressions)

problem two:
i will first define all of my variables which are marks , attended , classes attended , days excused and I will ask the user to input what they want.I also defined an equation to calculate the attendance percentage.Following will be nested if statements so first there will be an if statement to check whether the marks and attendance percentage followed by another if statement to check the days excused if its true it will print the first statement of not it will be followed by else and elif to reach the final statement to be printed in the code.(within all the statements i have used Booleon expression)

problem three:
I will declare the varaible which is the year and i will ask the user to input their choice then it will be followed by an if statement to check wether the year inserted is a multiple of 4 or 400 if its true it will print the first statement however if not an elif statement will be under and it will print the last statement.( within all of the statements I have used Booleon expresions)

## 1.2 Flowchart Diagram
"""

from IPython.display import Image
Image("flow chart#1") #porblem 1 flow chart

"""## 1.3 Explanation

Provide a detailed explanation of how your algorithm works.
my algorithm will work as followed

problem one:
It will first ask the user to input the delivery option followed by another iput of the weight of the package.Then if the user picks the express delivery option and the weight is less than 3 then the code will print "the cost is 40" if not the code will print "the cost is 40 +15". If not and the user picks the standard delivery option with a weight less than 3 the code will print "the cost is 25" if not the code will print "the cost is 25 + 10".Lalsty if not and the users picks the permium delivery option with a weight less than 3 then the code will print "the cost is 60" and if not any of these option the code will run and print " the cost is 60 + 25".

problem two:
In the begining the code will ask the user to enter the marks , attended, classes held and  days excused and then the code will calculate attenedance percentage.And then if the mark is 60 or higher and attendenace percentage is 85 ; and if the days excused is greater than or equal to 9 it will print (your absence are not excused, so you FAIL).Else  it will print (you passed).Else if the mark is greather than or equal 60 and the attendenace percentage is less than 85; it will print("you dont have the required attendance percentage, so you FAIL") else it will print ("you Failed").

Problem three:
The code will ask the user to input the year and then if the year inserted is a multiple of 4 or a multiple of 400 the code will print ("leap year") ; else if the year is a multiple of 100 the code will print ("not leap year").

# 2. Code

## 2.1 Import statements
"""

# include here all the modules that your code requires to run

"""## 2.2 Function definitions"""

# include here all the functions which your script will use

"""## 2.3 Script"""

#1
a = str(input("insert the delivery option"))
b = float(input("inser the weight of the package"))
if ((a=="express delivery") and (b<3)):
    print("the cost is:",40)
elif ((a=="express delivery") and (b>3)):
    print("the cost is:", 40 + 15)
elif ((a=="standrad delivery") and (b<3)):
    print("the cost is:",25)
elif ((a=="standrad delivery") and (b>3)):
    print("the cost is:",25 +10)
elif ((a=="permium delivery") and (b<3)):
    print("the cost is:", 60)
else:
    print("the cost is:", 60 +25)

#2
marks = float(input("insert the student's mark"))
attended = int(input("insert the number of classes attended"))
classes_held = int(input("insert the number of classes held"))
days_excused = int(input("insert the number of days excused"))
attended_percentage=(attended/classes_held)*100
if ((marks>60 and attended_percentage>85)):
    if days_excused>=9:
        print("your absence are not excused, so you FAIL")
    else:
        print("you passed")
elif((marks>60) and (attended_percentage<85)):
        print("you dont have the required attendance percentage, so you FAIL")
else:
    print("you Failed")

#3
year= int(input("insert the year"))
if year%4==0 or year%400==0:
    print("leap year")
elif year%100!=0:
    print("not leap year")

"""2.4 Test Cases

Problem one:
If the user picked the express delivery option and

#1
"""



"""## 2.5 Additional Code Description

Include any other details of your algorithmic approach or any other points here.

# 3. References

The references you used for your work will go here.
"""